### PR TITLE
attempt on fix pole camera look at jump

### LINKED ISSUE #75: Gimbal lock?
When rotate to the view from z-axis, further rotate cause random view angle jump. It seems like cause be the  gimbal lock.

### PR DESCRIPTION
**Pull request by unkcpz**
fixes #75 

Use arcball behavior and resolve the z-axis lock problem. The touch pan and touch zoom is also recovered.

### CODE REVIEW

File: vizmat-core/src/ui.rs [hunk 1]
```diff
@@ -3343,128 +3385,242 @@ pub(crate) fn camera_controls(
...
+            && !keyboard.pressed(KeyCode::ShiftLeft)
+        {
+            // This is a direct-view arcball control implementation.
+            if mouse_buttons.pressed(MouseButton::Left) {
+                rotate_request += mouse_delta;
+            }
+            if touch_rotate != Vec2::ZERO {
+                rotate_request += touch_rotate;
+            }
+            let window = windows.single().unwrap();
```
Comment (syzer) [inline vizmat-core/src/ui.rs]: Panic! 
return early would help: ex:
```js
  let (Ok(window), Ok((camera, camera_transform))) =
      (windows.single(), camera_query.single())
  else {
      return;
  };
```
